/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HiForm: typeof import('./src/components/HiForm/index.vue')['default']
    RenderFormItem: typeof import('./src/components/HiForm/components/RenderFormItem.vue')['default']
    RenderInput: typeof import('./src/components/HiForm/components/RenderInput.vue')['default']
    RenderSelect: typeof import('./src/components/HiForm/components/RenderSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
